/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Dice.glb -o Dice.tsx -r public -k 
*/
import {
  RigidBody,
  RapierRigidBody,
  interactionGroups,
  euler,
  quat,
} from "@react-three/rapier";
import { Euler, Group, Mesh, MeshStandardMaterial, Vector3 } from "three";
import { useFrame } from "@react-three/fiber";
import { useRef } from "react";
import { useGLTF, Edges } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    origin: Mesh;
    Dice_cell: Mesh;
    Dice_cell001: Mesh;
    Dice_cell002: Mesh;
    Dice_cell003: Mesh;
    Dice_cell004: Mesh;
    Dice_cell005: Mesh;
    Dice_cell006: Mesh;
    Dice_cell007: Mesh;
    Dice_cell008: Mesh;
    Dice_cell009: Mesh;
    Dice_cell010: Mesh;
    Dice_cell011: Mesh;
    Dice_cell012: Mesh;
    Dice_cell013: Mesh;
    Dice_cell014: Mesh;
    Dice_cell015: Mesh;
    Dice_cell016: Mesh;
    Dice_cell017: Mesh;
    Dice_cell018: Mesh;
    Dice_cell019: Mesh;
    Dice_cell020: Mesh;
    Dice_cell021: Mesh;
    Dice_cell022: Mesh;
    Dice_cell023: Mesh;
  };
  materials: {
    Dice: MeshStandardMaterial;
  };
};

export function Dice({
  dieId,
  position,
  rotation,
  rolling,
  reset,
  selectedDieId,
  exploded,
  setReset,
  setSelectedDieId,
}: {
  dieId: number;
  position: Vector3;
  rotation: Euler;
  rolling: boolean;
  reset: boolean;
  selectedDieId: number;
  exploded: boolean;
  setReset: (reset: boolean) => void;
  setSelectedDieId: (face: string, dieId: number) => void;
}) {
  const { nodes, materials } = useGLTF("/dice.glb") as GLTFResult;

  const piecesGroup = useRef<Group>(null);
  const originGroup = useRef<Group>(null);
  const origin = useRef<RapierRigidBody>(null);

  useFrame(() => {
    if (
      rolling &&
      origin.current &&
      piecesGroup.current &&
      originGroup.current
    ) {
      const randX = randomIntFromInterval(-3, 3);
      const randZ = randomIntFromInterval(-3, 3);
      origin.current.applyImpulse(new Vector3(randX, 5, randZ), true);
      origin.current.applyTorqueImpulse({ x: 3, y: 3, z: 3 }, true);
    }
    if (reset && origin.current && originGroup.current && piecesGroup.current) {
      origin.current.resetForces(false);
      origin.current.resetTorques(false);
      origin.current.setTranslation(position, false);
      originGroup.current.position.setX(position.x);
      originGroup.current.position.setY(position.y);
      originGroup.current.position.setZ(position.z);
      piecesGroup.current.position.setX(position.x);
      piecesGroup.current.position.setY(position.y);
      piecesGroup.current.position.setZ(position.z);
      setReset(false);
    }
  });

  function randomIntFromInterval(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1) + min);
  }

  function getDiceDetails() {
    if (!origin.current) {
      return;
    }
    const rot = euler().setFromQuaternion(quat(origin.current.rotation()));
    const x = getNormalizedDegree(rot.x);
    const y = getNormalizedDegree(rot.y);
    const z = getNormalizedDegree(rot.z);
    const die = getFace({ x, y, z });
    if (!die) {
      return;
    }
    return die.face;
  }

  function getNormalizedDegree(rotationValue: number) {
    const rotValue = rotationValue / (Math.PI / 180);
    let normalizedDegree = 0;
    if (rotValue > 45 && rotValue < 135) {
      normalizedDegree = 90;
    } else if (rotValue < -45 && rotValue > -135) {
      normalizedDegree = -90;
    } else if (
      (rotValue > 135 && rotValue < 215) ||
      (rotValue < -135 && rotValue > -215)
    ) {
      normalizedDegree = 180;
    }
    return normalizedDegree;
  }

  function getFace(degree: { x: number; y: number; z: number }) {
    const rotationLibrary = [
      { x: 0, y: 0, z: 0, face: "bombs" },
      { x: 0, y: 90, z: 0, face: "bombs" },
      { x: 180, y: 0, z: 180, face: "bombs" },
      { x: 0, y: -90, z: 0, face: "bombs" },
      { x: 180, y: 90, z: 180, face: "bombs" },
      { x: 180, y: -90, z: 180, face: "bombs" },
      { x: -90, y: 0, z: 0, face: "heads" },
      { x: -90, y: 0, z: 90, face: "heads" },
      { x: -90, y: 0, z: 180, face: "heads" },
      { x: -90, y: 0, z: -90, face: "heads" },
      { x: 0, y: 90, z: 90, face: "lanterns" },
      { x: 0, y: 0, z: 90, face: "lanterns" },
      { x: 90, y: 90, z: 0, face: "lanterns" },
      { x: -90, y: -90, z: 0, face: "lanterns" },
      { x: 0, y: -90, z: 90, face: "lanterns" },
      { x: -180, y: -180, z: 90, face: "lanterns" },
      { x: -90, y: 90, z: 180, face: "lanterns" },
      { x: 180, y: 90, z: -90, face: "lanterns" },
      { x: 180, y: 0, z: -90, face: "lanterns" },
      { x: 180, y: -90, z: -90, face: "lanterns" },
      { x: 180, y: 90, z: 90, face: "beers" },
      { x: 180, y: -90, z: 90, face: "beers" },
      { x: 0, y: 0, z: -90, face: "beers" },
      { x: 0, y: -90, z: -90, face: "beers" },
      { x: 90, y: -90, z: 0, face: "beers" },
      { x: -90, y: 90, z: 0, face: "beers" },
      { x: 180, y: 0, z: 90, face: "beers" },
      { x: 0, y: 90, z: -90, face: "beers" },
      { x: 90, y: 0, z: 0, face: "horns" },
      { x: 90, y: 0, z: -90, face: "horns" },
      { x: 90, y: 0, z: 180, face: "horns" },
      { x: 90, y: 0, z: 90, face: "horns" },
      { x: 90, y: 90, z: 90, face: "horns" },
      { x: 0, y: 0, z: 180, face: "axes" },
      { x: 180, y: -90, z: 0, face: "axes" },
      { x: 180, y: 90, z: 0, face: "axes" },
      { x: 180, y: 0, z: 0, face: "axes" },
      { x: 0, y: 90, z: 180, face: "axes" },
      { x: 0, y: -90, z: 180, face: "axes" },
    ];
    return rotationLibrary.find(function (obj) {
      if (obj.x === degree.x && obj.y === degree.y && obj.z === degree.z) {
        return obj;
      }
    });
  }

  function handleSelectedDie(dieId: number) {
    const face = getDiceDetails();
    if (!face) {
      return;
    }
    setSelectedDieId(face, dieId);
  }

  function getEdgeColor() {
    const face = getDiceDetails();
    switch (face) {
      case "beers":
        return "white";
      case "horns":
        return "white";
      case "axes":
        return "blue";
      case "bombs":
        return "red";
      case "lanterns":
        return "purple";
      case "heads":
        return "green";
    }
  }

  return (
    <group castShadow>
      <group position={position} rotation={rotation} ref={originGroup}>
        <RigidBody
          type="dynamic"
          name="origin"
          ref={origin}
          collisionGroups={interactionGroups(0, [0])}
          mass={1000}
          friction={0.2}
          linearDamping={0.2}
        >
          <mesh
            name="origin"
            geometry={nodes.origin.geometry}
            material={materials.Dice}
            visible={!exploded}
            onPointerOver={() => (document.body.style.cursor = "pointer")}
            onPointerOut={() => (document.body.style.cursor = "")}
            onPointerMissed={() => setSelectedDieId("", 0)}
            onClick={() => handleSelectedDie(dieId)}
          >
            <Edges
              visible={dieId === selectedDieId && !exploded && !rolling}
              linewidth={4}
              scale={1.02}
              threshold={15}
              color={getEdgeColor()}
            />
          </mesh>
        </RigidBody>
      </group>
      <group position={position} rotation={rotation} ref={piecesGroup}>
        <Pieces exploded={exploded} />
      </group>
    </group>
  );
}

function Pieces({ exploded }: { exploded: boolean }) {
  const { nodes, materials } = useGLTF("./dice.glb") as GLTFResult;

  const piecesGroup = useRef<Group>(null);

  const D0 = useRef<RapierRigidBody>(null);
  const D1 = useRef<RapierRigidBody>(null);
  const D2 = useRef<RapierRigidBody>(null);
  const D3 = useRef<RapierRigidBody>(null);
  const D4 = useRef<RapierRigidBody>(null);
  const D5 = useRef<RapierRigidBody>(null);
  const D6 = useRef<RapierRigidBody>(null);
  const D7 = useRef<RapierRigidBody>(null);
  const D8 = useRef<RapierRigidBody>(null);
  const D9 = useRef<RapierRigidBody>(null);
  const D10 = useRef<RapierRigidBody>(null);
  const D11 = useRef<RapierRigidBody>(null);
  const D12 = useRef<RapierRigidBody>(null);
  const D13 = useRef<RapierRigidBody>(null);
  const D14 = useRef<RapierRigidBody>(null);
  const D15 = useRef<RapierRigidBody>(null);
  const D16 = useRef<RapierRigidBody>(null);
  const D17 = useRef<RapierRigidBody>(null);
  const D18 = useRef<RapierRigidBody>(null);
  const D19 = useRef<RapierRigidBody>(null);
  const D20 = useRef<RapierRigidBody>(null);
  const D21 = useRef<RapierRigidBody>(null);
  const D22 = useRef<RapierRigidBody>(null);
  const D23 = useRef<RapierRigidBody>(null);

  return (
    <group ref={piecesGroup} visible={exploded} castShadow receiveShadow>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D0}
        name="D0"
        collisionGroups={interactionGroups(1, [1])}
        mass={100}
        friction={0.2}
      >
        <mesh
          name="Dice_cell"
          geometry={nodes.Dice_cell.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D1}
        name="D1"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell001"
          geometry={nodes.Dice_cell001.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D2}
        name="D2"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell002"
          geometry={nodes.Dice_cell002.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D3}
        name="D3"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell003"
          geometry={nodes.Dice_cell003.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D4}
        name="D4"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell004"
          geometry={nodes.Dice_cell004.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D5}
        name="D5"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell005"
          geometry={nodes.Dice_cell005.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D6}
        name="D6"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell006"
          geometry={nodes.Dice_cell006.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D7}
        name="D7"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell007"
          geometry={nodes.Dice_cell007.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D8}
        name="D8"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell008"
          geometry={nodes.Dice_cell008.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D9}
        name="D9"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell009"
          geometry={nodes.Dice_cell009.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D10}
        name="D10"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell010"
          geometry={nodes.Dice_cell010.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D11}
        name="D11"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell011"
          geometry={nodes.Dice_cell011.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D12}
        name="D12"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell012"
          geometry={nodes.Dice_cell012.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D13}
        name="D13"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell013"
          geometry={nodes.Dice_cell013.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D14}
        name="D14"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell014"
          geometry={nodes.Dice_cell014.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D15}
        name="D15"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell015"
          geometry={nodes.Dice_cell015.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D16}
        name="D16"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell016"
          geometry={nodes.Dice_cell016.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D17}
        name="D17"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell017"
          geometry={nodes.Dice_cell017.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D18}
        name="D18"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell018"
          geometry={nodes.Dice_cell018.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D19}
        name="D19"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell019"
          geometry={nodes.Dice_cell019.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D20}
        name="D20"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell020"
          geometry={nodes.Dice_cell020.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D21}
        name="D21"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell021"
          geometry={nodes.Dice_cell021.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D22}
        name="D22"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell022"
          geometry={nodes.Dice_cell022.geometry}
          material={materials.Dice}
        />
      </RigidBody>
      <RigidBody
        type={exploded ? "dynamic" : "fixed"}
        ref={D23}
        name="D23"
        collisionGroups={interactionGroups(1, [1])}
        mass={20}
      >
        <mesh
          name="Dice_cell023"
          geometry={nodes.Dice_cell023.geometry}
          material={materials.Dice}
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/dice.glb");
